# common values shared between all charts

global:
  gateway:
    # global.gateway.domain -- configure default domain for gateway host, i.e. "{{ .Release.Name }}.127.0.0.1.nip.io"
    domain: ""
    # global.gateway.host -- configure default gateway host Helm template, i.e. "activiti-cloud-gateway.{{ .Values.global.gateway.domain }}"
    host: ""
    # global.gateway.http -- toggle creating http or https ingress rules, supports literal or boolean values
    http: true
    # global.gateway.tlsacme -- used to enable automatic TLS for ingress if http is false
    tlsacme: false

  keycloak:
    enabled: true
    # keycloak.url -- overrides gateway host configuration
    url: ""
    # keycloak.path -- configure default keycloak path
    path: "/auth"
    ## Configure default keycloak host template, i.e "activiti-keycloak.{{ .Values.global.gateway.domain }}"
    host: ""
    # keycloak.realm -- configure default Keycloak realm
    realm: "activiti"
    # keycloak.resource -- configure default Keycloak resource
    resource: "activiti"
    # keycloak.extraEnv -- adds Keycloak extraEnv to deployments
    extraEnv: ""

  # global.registryPullSecrets -- configure pull secrets for all deployments
  registryPullSecrets: []

  # global.extraEnv -- adds global extraEnv to deployments
  extraEnv: ""

  extraInitContainers: ""

# extraEnv -- adds extraEnv to deployments
extraEnv: ""

# registryPullSecrets -- configures additional pull secrets for this deployment
registryPullSecrets: []

## Allows to template gateway values from Jx Expose controller configuration in GitOps environment, i.e.
# expose:
#   config:
#     domain: 1.2.3.4.nip.io
#     http: "true"
#     tlsacme: "false"
#
# global:
#   keycloak:
#     host: "activiti-keycloak.{{ tpl .Values.global.gateway.domain . }}"
#   gateway:
#     domain: "{{ .Values.expose.config.domain }}"
#     http: "{{ .Values.expose.config.http }}"
#     tlsacme: "{{ .Values.expose.config.tlsacme }}"
expose:
  config:
    domain: ""
    http: "true"
    tlsacme: "false"

ingress:
  enabled: false
  # ingress.tls -- set this to true in order to enable TLS on the ingress record
  tls:
  # ingress.path -- set ingress path
  # @default empty, each ingress should provide its own value or template
  path:
  # ingress.subPaths -- set multiple ingress subpaths
  subPaths:
  # ingress.tlsSecret -- if TLS is set to true, you must declare what secret will store the key/certificate for TLS
  tlsSecret:
  # ingress.hostName -- if set, overrides .Values.global.gateway.host configuration
  hostName:
  # ingress.annotations -- configure default ingress annotations
  annotations: {}

# nodeSelector -- allows customising nodeSelector
nodeSelector: {}

# tolerations -- allows customising tolerations
tolerations: []

# affinity -- allows customising affinity
affinity: {}
