# common values shared between all charts

global:
  gateway:
    # global.gateway.domain -- configure default domain for gateway host, i.e. "{{ .Release.Name }}.127.0.0.1.nip.io"
    domain: ""
    # global.gateway.host -- configure default gateway host Helm template, i.e. "gateway.{{ .Values.global.gateway.domain }}"
    host: ""
    # global.gateway.http -- toggle creating http or https ingress rules, supports literal or boolean values
    http: true
    # global.gateway.tlsacme -- used to enable automatic TLS for ingress if http is false
    tlsacme: false

  keycloak:
    enabled: true
    # global.keycloak.url -- overrides gateway host configuration
    url: ""
    # global.keycloak.path -- configure default keycloak path
    path: "/auth"
    # global.keycloak.host -- configure default keycloak host template, i.e "identity.{{ .Values.global.gateway.domain }}"
    host: ""
    # global.keycloak.realm -- configure default Keycloak realm
    realm: "activiti"
    # global.keycloak.resource -- configure default Keycloak resource
    resource: "activiti"
    # global.keycloak.client -- obsolete, same as global.keycloak.resource
    client: "activiti"
    # global.keycloak.extraEnv -- adds Keycloak extraEnv to deployments
    extraEnv: ""

  # global.registryPullSecrets -- configure pull secrets for all deployments
  registryPullSecrets: []

  # global.extraEnv -- adds global extraEnv to deployments
  extraEnv: ""

  extraInitContainers: ""

# extraEnv -- adds extraEnv to deployments
extraEnv: ""

# registryPullSecrets -- configures additional pull secrets for this deployment
registryPullSecrets: []

ingress:
  enabled: false
  # ingress.tls -- set this to true in order to enable TLS on the ingress record
  tls:
  # ingress.path -- set ingress path
  # @default empty, each ingress should provide its own value or template
  path:
  # ingress.subPaths -- set multiple ingress subpaths
  subPaths:
  # ingress.tlsSecret -- if TLS is set to true, you must declare what secret will store the key/certificate for TLS
  tlsSecret:
  # ingress.hostName -- if set, overrides .Values.global.gateway.host configuration
  hostName:
  # ingress.annotations -- configure default ingress annotations
  annotations: {}

# nodeSelector -- allows customising nodeSelector
nodeSelector: {}

# tolerations -- allows customising tolerations
tolerations: []

# affinity -- allows customising affinity
affinity: {}
