repos:
  - repo: https://github.com/norwoodj/helm-docs
    rev: v1.4.0
    hooks:
      - id: helm-docs
  - repo: https://github.com/Alfresco/alfresco-build-tools
    rev: v1.4.0
    hooks:
      - id: helm-deps
      - id: helm-lint
      - id: kubepug-minimum
      - id: kubepug-recommended
      - id: checkov-helm
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/sirosen/check-jsonschema
    rev: 0.17.0
    hooks:
      - id: check-github-workflows
      - id: check-jsonschema
        alias: check-dependabot
        name: "Validate Dependabot Config"
        files: '.github/dependabot\.yml$'
        args: ["--schemafile", "https://json.schemastore.org/dependabot-2.0.json"]
