repos:
  - repo: https://github.com/norwoodj/helm-docs
    rev: v1.4.0
    hooks:
      - id: helm-docs
  - repo: https://github.com/Alfresco/alfresco-build-tools
    rev: v1.1.0
    hooks:
      - id: helm-deps
      - id: helm-lint
      - id: kubepug-minimum
      - id: kubepug-recommended
      - id: checkov-helm
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
