github:
  organisations:
  - name: activiti
    repositories:
    - name: example-cloud-connector
      branch: master
      useSinglePullRequest: true
    - name: example-runtime-bundle
      branch: master
      useSinglePullRequest: true
    - name: activiti-cloud-modeling
      branch: master
      useSinglePullRequest: true
    - name: activiti-cloud-query
      branch: master
      useSinglePullRequest: true
    - name: activiti-cloud-dependencies
      useSinglePullRequest: true
    - name: activiti-cloud-identity-chart
      useSinglePullRequest: true
