github:
  organisations:
  - name: activiti
    repositories:
    - name: activiti-cloud-application
      branch: develop
      useSinglePullRequest: true
    - name: activiti-cloud-identity-chart
      branch: master
      useSinglePullRequest: true
