{{/*
Create SPRING_DATASOURCE_* env.
*/}}
{{- define "common.spring-datasource-env" -}}
- name: SPRING_DATASOURCE_URL
  value: {{ with .Values.db.uri }}{{ tpl . $ }}{{ else }}{{ tpl "jdbc:postgresql://{{ include \"common.postgresql.fullname\" . }}:{{ .Values.postgresql.port }}/{{ .Values.db.username }}" . }}{{ end }}
- name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
  value: {{ .Values.db.driver }}
- name: SPRING_DATASOURCE_USERNAME
  value: {{ .Values.db.username }}
- name: SPRING_DATASOURCE_PASSWORD
  {{- if .Values.db.password }}
  value: {{ .Values.db.password | quote }}
  {{- else if .Values.postgresql.enabled }}
  valueFrom:
    secretKeyRef:
      name: {{ include "common.postgresql.fullname" . }}
      key: postgresql-password
  {{- else }}
  value: ""
  {{- end }}
{{- end -}}

{{/*
Create SPRING_JPA_* env.
*/}}
{{- define "common.spring-jpa-env" -}}
- name: SPRING_JPA_DATABASE_PLATFORM
  value: {{ .Values.db.platform }}
- name: SPRING_JPA_GENERATE_DDL
  value: {{ .Values.db.generateDdl | quote }}
- name: SPRING_JPA_HIBERNATE_DDL_AUTO
  value: {{ .Values.db.ddlAuto }}
{{- end -}}

{{/*
Create keycloak env.
*/}}
{{- define "common.keycloak-env" }}
- name: ACT_KEYCLOAK_URL
  value: {{ include "common.keycloak-url" . }}
  {{- with include "common.keycloak-realm" . }}
- name: ACT_KEYCLOAK_REALM
  value: {{ . }}
  {{- end }}
  {{- with include "common.keycloak-resource" . }}
- name: ACT_KEYCLOAK_RESOURCE
  value: {{ . }}
  {{- end -}}
{{- end }}

{{/*
Create backend service.envType env.
*/}}
{{- define "common.backend-env" -}}
- name: JAVA_OPTS
  value: "-Xmx{{ .Values.javaOpts.xmx }} -Xms{{ .Values.javaOpts.xms }} {{ .Values.javaOpts.other}}"
- name: SPRING_APPLICATION_NAME
  value: {{ .Values.service.name | default (include "common.fullname" .) }}
{{- if or .Values.rabbitmq.enabled .Values.global.rabbitmq.enabled }}
- name: SPRING_RABBITMQ_HOST
  value: {{ tpl (coalesce .Values.rabbitmq.host .Values.global.rabbitmq.host) $ | required "rabbitmq.host is required" }}
- name: SPRING_RABBITMQ_USERNAME
  value: {{ coalesce .Values.rabbitmq.username .Values.global.rabbitmq.username }}
- name: SPRING_RABBITMQ_PASSWORD
  value: {{ coalesce .Values.rabbitmq.password .Values.global.rabbitmq.password }}
{{- end }}
{{- if or .Values.kafka.enabled .Values.global.kafka.enabled }}
- name:  SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS
  value: {{ tpl (coalesce .Values.kafka.brokers .Values.global.kafka.brokers) $ | required "kafka.brokers is required" }}
- name:  SPRING_CLOUD_STREAM_KAFKA_BINDER_DEFAULTBROKERPORT
  value: {{ coalesce .Values.kafka.port .Values.global.kafka.port "9092" | quote }}
- name: SPRING_CLOUD_STREAM_KAFKA_BINDER_ZK_NODES
  value: {{ tpl (coalesce .Values.kafka.zkNodes .Values.global.kafka.zkNodes) $ | required "kafka.zkNodes is required" }}
- name: SPRING_CLOUD_STREAM_KAFKA_BINDER_DEFAULTZKPORT
  value: {{ coalesce .Values.kafka.zkPort .Values.global.kafka.zkPort "2181" | quote }}
- name: ACT_AUDIT_PRODUCER_TRANSACTION_ID_PREFIX
  value: {{ coalesce .Values.kafka.trxIdPrefix .Values.global.kafka.trxIdPrefix | default "" | quote }}
{{- end }}
{{- if include "common.keycloak-enabled" . }}
{{ include "common.keycloak-env" . }}
{{- end }}
{{- if or .Values.db.uri .Values.postgresql.enabled }}
{{ include "common.spring-datasource-env" . }}
{{ include "common.spring-jpa-env" . }}
{{- if .Values.liquibase.enabled }}
- name: SPRING_LIQUIBASE_ENABLED
  value: "false"
{{ end }}
{{- end }}
{{- end }}
