{{- define "common.deployment.head" -}}
apiVersion: apps/v1
kind: {{ if .Values.statefulset.enabled }}StatefulSet{{ else }}Deployment{{ end }}
metadata:
  name: {{ template "common.fullname" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
{{- end -}}
