{{- define "common.ingress.tpl" -}}
{{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1" -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ template "common.fullname" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
  {{- with (include "common.ingress-annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
spec:
  rules:
    {{- with (include "common.ingress-host" .) }}
    - host: {{ . }}
      http:
    {{- else }}
    - http:
    {{- end }}
        paths:
          {{- $serviceName := .Values.service.name -}}
          {{- $externalPort := .Values.service.externalPort -}}
          {{- $ingressPath := include "common.ingress-path" . -}}
          {{- $serviceNameTemplate := include "common.fullname" . -}}
          {{- $paths := list }}
          {{- if .Values.ingress.subPaths -}}
            {{- range .Values.ingress.subPaths }}
              {{- $path := list $ingressPath . | join "" }}
              {{- $paths = append $paths $path }}
            {{- end }}
          {{- else -}}
            {{- $paths = append $paths $ingressPath }}
          {{- end -}}
          {{- range $paths }}
            - path: {{ . }}
              {{- if $.Capabilities.APIVersions.Has "networking.k8s.io/v1" }}
              pathType: Prefix
              backend:
                service:
                  name: {{ coalesce $serviceName $serviceNameTemplate }}
                  port:
                    number: {{ $externalPort }}
              {{- else }}
              backend:
                serviceName: {{ coalesce $serviceName $serviceNameTemplate }}
                servicePort: {{ $externalPort }}
              {{- end }}
          {{- end }}
  {{- if include "common.ingress-tls" . }}
  tls:
    - secretName: {{ template "common.ingress-tlssecretname" . }}
      {{- with (include "common.ingress-host" .) }}
      hosts:
        - {{ . }}
      {{- end }}
  {{- end }}
{{- end }}
{{- define "common.ingress" -}}
  {{- if index (first .) "Values" "ingress" "enabled" -}}
    {{- template "common.util.merge" (append . "common.ingress.tpl") -}}
  {{- end -}}
{{- end -}}
