{{- define "common.probes.tpl" -}}
livenessProbe:
  httpGet:
    path: {{ tpl .Values.probePath . }}
    port: {{ .Values.service.internalPort }}
  initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
  periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
  successThreshold: {{ .Values.livenessProbe.successThreshold }}
  timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
  failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
  readinessProbe:
    httpGet:
      path: {{ tpl .Values.probePath . }}
      port: {{ .Values.service.internalPort }}
    initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
    periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
    successThreshold: {{ .Values.readinessProbe.successThreshold }}
    timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
    failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
{{- end -}}