{{- define "common.service" -}}
{{- template "common.util.merge" (append . "common.service.tpl") -}}
{{- end -}}

{{- define "common.service.tpl" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "common.service.name" . }}
  labels:
  {{ include "common.labels.standard" . | indent 4 }}
  annotations:
  {{ include "common.service.annotations.tpl" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.externalPort }}
    targetPort: {{ .Values.service.internalPort }}
    {{- if (and (eq .Values.service.type "NodePort") (not (empty .Values.service.nodePort))) }}
    nodePort: {{ .Values.service.nodePort }}
    {{- end }}
    protocol: TCP
    name: http
  selector:
    app: {{ template "common.fullname" . }}
{{- end -}}

{{- define "common.service.name" -}}
{{ .Values.service.name | default (include "common.fullname" .) | quote }}
{{- end -}}

{{- define "common.service.annotations.tpl" }}
{{ tpl (toYaml (.Values.service.annotations | default (dict ))) . }}
{{- end }}