{{- define "common.service.tpl" -}}
{{/* magic one-liner to get values merged from common and chart */}}
{{- $values := index (merge (omit . "Values") (dict "Values" (omit .Values "common")) (dict "Values" .Values.common)) "Values" -}}
apiVersion: v1
kind: Service
metadata:
{{- if $values.service.name }}
  name: {{ $values.service.name }}
{{- else }}
  name: {{ template "fullname" . }}
{{- end }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
{{- if $values.service.annotations }}
  annotations:
    {{ toYaml $values.service.annotations | nindent 4 }}
{{- end }}
spec:
  type: {{ $values.service.type }}
  ports:
  - port: {{ $values.service.externalPort }}
    targetPort: {{ $values.service.internalPort }}
    {{- with $values.service.nodePort }}
    nodePort: {{ . }}
    {{- end }}
    protocol: TCP
    name: http
  selector:
    {{- include "common.selectorLabels" . | nindent 4 }}
{{- end -}}
{{- define "common.service" -}}
{{- template "common.util.merge" (append . "common.service.tpl") -}}
{{- end -}}
