{{/*
Create the name of the service account to use
*/}}
{{- define "common.serviceAccountName" -}}
{{- if .Values.serviceAccount.create }}
{{- default (include "common.fullname" .) .Values.serviceAccount.name }}
{{- else }}
{{- default "default" .Values.serviceAccount.name }}
{{- end }}
{{- end -}}

{{- define "common.serviceaccount.tpl" -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "common.serviceAccountName" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- range $key, $val := . }}
    {{ $key }}: {{ tpl (toString $val) $ | quote }}
    {{- end }}
  {{- end }}
{{- end -}}

{{- define "common.serviceaccount" -}}
  {{- if index (first .) "Values" "serviceAccount" "create" -}}
    {{- template "common.util.merge" (append . "common.serviceaccount.tpl") -}}
  {{- end -}}
{{- end -}}
