{{- define "common.statefulset.tpl" -}}
apiVersion: apps/v1
kind: StatefulSet
{{ template "common.metadata" . }}
spec:
  selector:
    matchLabels:
      app: {{ template "common.name" . }} # has to match .spec.template.metadata.labels
{{- if .Values.service.name }}
  serviceName: {{ .Values.service.name }}
{{- else }}
  serviceName: {{ template "common.fullname" . }}
{{- end }}      
  template:
    metadata:
      labels:
        app: {{ template "common.name" . }}
        release: {{ .Release.Name | quote }}
    spec:
      containers:
      -
{{ include "common.container.tpl" . | indent 8 }}
{{- end -}}
{{- define "common.statefulset" -}}
{{- template "common.util.merge" (append . "common.statefulset.tpl") -}}
{{- end -}}