name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the default branch
  push:
    branches: [ master, dev-elias-3898-gh-actions ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  pre-commit:
    runs-on: ubuntu-20.04
    steps:
      - uses: Alfresco/alfresco-build-tools/.github/actions/run-pre-commit-for-helm@dev-elias-3898-gh-actions

  build:
    runs-on: ubuntu-20.04
    needs: pre-commit
    steps:
      - uses: actions/checkout@v3
      - name: build
        run: |
          yq e '.version' charts/common/Chart.yaml > VERSION
          cd ./charts/common
          make build
          make test

  publish:
    runs-on: ubuntu-20.04
    needs: build
    if: ${{ github.event_name == 'push' }}
    steps:
      - uses: Alfresco/alfresco-build-tools/.github/actions/setup-updatebot@v1.3.0
      - uses: Alfresco/alfresco-build-tools/.github/actions/setup-helm-docs@v1.3.0
      - uses: actions/checkout@v3
      - id: next-release
        name: Calculate next internal release
        uses: Alfresco/alfresco-build-tools/.github/actions/calculate-next-internal-version@dev-elias-3898-gh-actions
        with:
          next-version: 7.3.0

      - name: Update VERSION file
        run: echo ${{steps.next-release.outputs.next-prerelease}} > VERSION

      - name: Configure git user
        uses: Alfresco/alfresco-build-tools/.github/actions/configure-git-user@dev-elias-3898-gh-actions
        with:
          username: ${{ secrets.BOT_GITHUB_USERNAME }}

      - name: publish
        run: |
          cd ./charts/common
          make version
          make tag
          make release
          make github
          make updatebot/push-version
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
