name: CI

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
    types:
      - opened
      - reopened
      - synchronize
      - labeled
  workflow_dispatch:

env:
  CHART_NAME: common
  CHART_DIR: charts/common
  HELM_REPO: Activiti/activiti-cloud-helm-charts
  HELM_REPO_NAME: activiti-cloud-helm-charts
  HELM_REPO_BASE_URL: https://activiti.github.io/activiti-cloud-helm-charts
  HELM_REPO_BRANCH: gh-pages
  HELM_REPO_SUBFOLDER: .

jobs:

  pre-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Check dependabot build
        uses: Activiti/Activiti/.github/actions/check-ext-build@4db084fcbb13a288f3b66ac08fc50a5ab7f144ed # 8.0.0-alpha.10
      - name: Setup Helm Docs
        uses: Alfresco/alfresco-build-tools/.github/actions/setup-helm-docs@dc4c1f4e94307af7a916d0ca8c5e2592521d9470 # v5.22.3
      - name: Run Checkov
        uses: bridgecrewio/checkov-action@e1bb78184f5dd3690fb1089d6c4f51295f9dff48 # v12.1839.0
        with:
          framework: kubernetes
      - name: pre-commit
        uses: Alfresco/alfresco-build-tools/.github/actions/pre-commit@dc4c1f4e94307af7a916d0ca8c5e2592521d9470 # v5.22.3
        with:
          skip_checkout: true
      - name: Ensure SHA pinned actions
        uses: zgosalvez/github-actions-ensure-sha-pinned-actions@19ebcb0babbd282ae1822a0b9c28f3f1f25cea45 # v3.0.4

  build:
    runs-on: ubuntu-latest
    needs: pre-checks
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Build
        uses: Alfresco/alfresco-build-tools/.github/actions/helm-build-chart@dc4c1f4e94307af7a916d0ca8c5e2592521d9470 # v5.22.3
        with:
          chart-dir: ${{ env.CHART_DIR }}

      - name: Setup Helm test plugin
        run: helm plugin install https://github.com/helm-unittest/helm-unittest.git --version v0.3.2

      - name: Test
        run: helm unittest $CHART_DIR

  publish:
    runs-on: ubuntu-latest
    needs: build
    outputs:
      version: ${{ steps.calculate-next-internal-version.outputs.next-prerelease }}
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Parse next release
        id: helm-parse-next-release
        uses: Alfresco/alfresco-build-tools/.github/actions/helm-parse-next-release@dc4c1f4e94307af7a916d0ca8c5e2592521d9470 # v5.22.3
        with:
          chart-dir: ${{ env.CHART_DIR }}

      - id: calculate-next-internal-version
        name: Calculate next internal release
        uses: Alfresco/alfresco-build-tools/.github/actions/calculate-next-internal-version@dc4c1f4e94307af7a916d0ca8c5e2592521d9470 # v5.22.3
        with:
          next-version: ${{ steps.helm-parse-next-release.outputs.next-release }}

      - id: helm-release-and-publish
        name: Release and publish helm chart
        uses: Alfresco/alfresco-build-tools/.github/actions/helm-release-and-publish@dc4c1f4e94307af7a916d0ca8c5e2592521d9470 # v5.22.3
        with:
          version: ${{ steps.calculate-next-internal-version.outputs.next-prerelease }}
          chart-dir: ${{ env.CHART_DIR }}
          helm-repository: ${{ env.HELM_REPO }}
          helm-repository-branch: ${{ env.HELM_REPO_BRANCH }}
          helm-repository-subfolder: ${{ env.HELM_REPO_SUBFOLDER }}
          helm-repository-base-url: ${{ env.HELM_REPO_BASE_URL }}
          helm-repository-token: ${{ secrets.BOT_GITHUB_TOKEN }}
          git-username: ${{ secrets.BOT_GITHUB_USERNAME }}
          do-push: ${{ github.event_name == 'push' }}

  propagate:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: publish
    env:
      VERSION: ${{ needs.publish.outputs.version }}
      DEVELOPMENT_BRANCH: ${{ github.ref_name }}
    steps:
      - uses: Activiti/activiti-scripts/.github/actions/wait-for-chart@000995bdf3eae49f78ff39c462226208039ef1a8 # 8.1.0
        with:
          chart-name: ${{ env.CHART_NAME }}
          version: ${{ env.VERSION }}
          helm-repo-name:  ${{ env.HELM_REPO_NAME }}
          helm-repo-url: ${{ env.HELM_REPO_BASE_URL }}
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: Alfresco/alfresco-build-tools/.github/actions/setup-helm-docs@dc4c1f4e94307af7a916d0ca8c5e2592521d9470 # v5.22.3
      - uses: Alfresco/alfresco-build-tools/.github/actions/jx-updatebot-pr@dc4c1f4e94307af7a916d0ca8c5e2592521d9470 # v5.22.3
        env:
          GH_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
        with:
          version: ${{ env.VERSION }}
          auto-merge: 'true'
          labels: ${{ env.DEVELOPMENT_BRANCH }}
          base-branch-name: ${{ env.DEVELOPMENT_BRANCH }}
          git-username: ${{ secrets.BOT_GITHUB_USERNAME }}
          git-token: ${{ secrets.BOT_GITHUB_TOKEN }}
          git-author-name: ${{ secrets.BOT_GITHUB_USERNAME }}
          git-author-email: ${{ secrets.BOT_GITHUB_USERNAME }}@users.noreply.github.com

  notify:
    runs-on: ubuntu-latest
    needs:
      - propagate
    if: always() && failure() && github.event_name == 'push'
    steps:
      - name: Slack Notification
        uses: Alfresco/alfresco-build-tools/.github/actions/send-slack-notification@dc4c1f4e94307af7a916d0ca8c5e2592521d9470 # v5.22.3
        with:
          channel-id: 'eng-hxp-studio-activiti-gh-notifs'
          token: ${{ secrets.SLACK_NOTIFICATION_BOT_TOKEN }}
