name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the default branch
  push:
    branches: [ master, gh-3898-move-actions-from-make ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  CHARTS_PATH: "charts/common"

jobs:
  pre-commit:
    runs-on: ubuntu-20.04
    steps:
      - uses: Alfresco/alfresco-build-tools/.github/actions/setup-helm-docs@v1.4.0
      - uses: Alfresco/alfresco-build-tools/.github/actions/setup-kubepug@v1.4.0
      - uses: Alfresco/alfresco-build-tools/.github/actions/setup-checkov@v1.4.0
      - uses: Alfresco/alfresco-build-tools/.github/actions/pre-commit@v1.4.0

  build:
    runs-on: ubuntu-20.04
    needs: pre-commit
    steps:
      - uses: actions/checkout@v3

      - name: Build
        uses: ./.github/actions/build-helm-chart
        with:
          - chart-path: ${{ env.CHARTS_PATH }}

      - name: Setup Helm test plugin
        run: helm plugin install https://github.com/quintush/helm-unittest

      - name: Test
        run: helm unittest ${{ env.CHARTS_PATH }} --helm3

  publish:
    runs-on: ubuntu-20.04
    needs: build
    if: ${{ github.event_name == 'push' }}
    steps:
      - uses: Alfresco/alfresco-build-tools/.github/actions/setup-updatebot@v1.4.0
      - uses: Alfresco/alfresco-build-tools/.github/actions/setup-helm-docs@v1.4.0
      - uses: actions/checkout@v3
      - id: next-release
        name: Calculate next internal release
        uses: Alfresco/alfresco-build-tools/.github/actions/calculate-next-internal-version@v1.4.0
        with:
          next-version: 7.4.0

      - name: Update VERSION file
        run: echo ${{steps.next-release.outputs.next-prerelease}} > VERSION

      - name: publish
        run: |
          git config --global user.name $GITHUB_USERNAME
          git config --global user.email $GITHUB_USERNAME@users.noreply.github.com
          echo -e "https://$GITHUB_USERNAME:$GITHUB_TOKEN@github.com" >>  ~/.git-credentials
          cd ./charts/common
          make version
          make tag
          make release
          make github
          make updatebot/push-version
        env:
          GITHUB_USERNAME: ${{ secrets.BOT_GITHUB_USERNAME }}
          GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
