name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the default branch
  push:
    branches: [ master, gh-3898-move-actions-from-make ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  CHART_DIR: "charts/common"

jobs:
  pre-commit:
    runs-on: ubuntu-20.04
    steps:
      - uses: Alfresco/alfresco-build-tools/.github/actions/setup-helm-docs@v1.4.0
      - uses: Alfresco/alfresco-build-tools/.github/actions/setup-kubepug@v1.4.0
      - uses: Alfresco/alfresco-build-tools/.github/actions/setup-checkov@v1.4.0
      - uses: Alfresco/alfresco-build-tools/.github/actions/pre-commit@v1.4.0

  build:
    runs-on: ubuntu-20.04
    needs: pre-commit
    steps:
      - uses: actions/checkout@v3

      - name: Build
        uses: ./.github/actions/build-helm-chart
        with:
          chart-dir: ${{ env.CHART_DIR }}

      - name: Setup Helm test plugin
        run: helm plugin install https://github.com/quintush/helm-unittest

      - name: Test
        run: helm unittest $CHART_DIR --helm3

  publish:
    runs-on: ubuntu-20.04
    needs: build
    if: ${{ github.event_name == 'push' }}
    outputs:
      version: ${{ steps.next-release.outputs.next-prerelease }}
    steps:
      - uses: actions/checkout@v3

      - id: next-release
        name: Calculate next internal release
        uses: Alfresco/alfresco-build-tools/.github/actions/calculate-next-internal-version@v1.4.0
        with:
          next-version: 7.4.0

      - name: Set version env variable
        env:
          VERSION: ${{ steps.next-release.outputs.next-prerelease }}
        run: |
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Update chart version
        uses: ./.github/actions/update-chart-version
        with:
          new-version: ${{env.VERSION}}
          chart-dir: ${{ env.CHART_DIR }}

      - name: Create local tag
        env:
          GITHUB_USERNAME: ${{ secrets.BOT_GITHUB_USERNAME }}
        run: |
          git config --global user.name $GITHUB_USERNAME
          git config --global user.email $GITHUB_USERNAME@users.noreply.github.com
          git add -u
          git status
          git --no-pager diff --cached
          git commit -m "release $VERSION"
          git tag -a $VERSION -m "Release version $VERSION"


      - name: Package Helm Chart
        id: package-helm-chart
        uses: ./.github/actions/package-helm-chart
        with:
          chart-dir: ${{ env.CHART_DIR }}

      - name: Push tag
        run: git push origin $VERSION

      - name: Publish Helm chart
        uses: ./.github/actions/publish-helm-chart
        with:
            helm-chart-repository: Activiti/activiti-cloud-helm-charts
            chart-package: ${{ steps.package-helm-chart.outputs.package-file }}
            token: ${{ secrets.BOT_GITHUB_TOKEN}}

  propagate:
    runs-on: ubuntu-20.04
    needs: publish
    if: ${{ github.event_name == 'push' }}
    env:
      FULL_CHART_DIR: full-chart
      FULL_CHART_BRANCH: develop
      VERSION: ${{ needs.publish.outputs.version }}
    steps:
      - uses: actions/checkout@v3
        with:
          path: $FULL_CHART_DIR
          repository: Activiti/activiti-cloud-full-chart
          ref: $FULL_CHART_BRANCH
          token: ${{ secrets.BOT_GITHUB_TOKEN }}

      - uses: Alfresco/alfresco-build-tools/.github/actions/setup-helm-docs@v1.4.0

      - name: Update full chart to use new version of common
        run: |
          cd $FULL_CHART_DIR
          yq e '(.dependencies.[] | select(.name == "common").version) = env(VERSION)' -i charts/activiti-cloud-full-example/requirements.yaml
          helm-docs
          git status
          git --no-pager diff

      - name: Create Propagation Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
          path: ${{ env.FULL_CHART_DIR }}
          commit-message: $COMMIT_MESSAGE
          committer: $GITHUB_USERNAME
          branch: ${FULL_CHART_BRANCH}-update-common
          delete-branch: true
          title: $COMMIT_MESSAGE
        env:
          COMMIT_MESSAGE: Bump activiti-cloud-common charts to version ${{ env.VERSION }}
          GITHUB_USERNAME: ${{ secrets.BOT_GITHUB_USERNAME }}
