name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the default branch
  push:
    branches: [ master, dev-elias-3898-gh-actions ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  pre-commit:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
      - uses: Alfresco/alfresco-build-tools/.github/actions/setup-helm-docs@v1.3.0
      - uses: Alfresco/alfresco-build-tools/.github/actions/setup-kubepug@master
      - uses: Alfresco/alfresco-build-tools/.github/actions/setup-checkov@master
      - uses: pre-commit/action@v2.0.3

  build:
    runs-on: ubuntu-20.04
    needs: pre-commit
    steps:
      - uses: actions/checkout@v3
      - name: build
        run: |
          yq e '.version' charts/common/Chart.yaml > VERSION
          cd ./charts/common
          make build
          make test

  publish:
    runs-on: ubuntu-20.04
    needs: build
    if: ${{ github.event_name == 'push' }}
    steps:
      - name: Install updatebot
        uses: Alfresco/alfresco-build-tools/.github/actions/setup-updatebot@v1.3.0

      - uses: Alfresco/alfresco-build-tools/.github/actions/setup-helm-docs@v1.3.0
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
      - uses: Alfresco/alfresco-build-tools/.github/actions/setup-pysemver@v1.3.0
      - id: next-release
        name: Calculate next internal release
        uses: Alfresco/alfresco-build-tools/.github/actions/calculate-next-internal-version@v1.3.0
        with:
          next-version: 7.3.0

      - name: Update VERSION file
        run: echo ${{steps.next-release.outputs.next-prerelease}} > VERSION

      - name: Configure git user
        if: ${{ github.event_name == 'push' }}
        run: |
          git config --global user.name $GITHUB_USERNAME
          git config --global user.email $GITHUB_USERNAME@users.noreply.github.com
        env:
          GITHUB_USERNAME: ${{ secrets.BOT_GITHUB_USERNAME }}

      - name: publish
        run: |
          git config --global user.email "${GITHUB_USER_EMAIL}"
          echo -e "https://$GITHUB_USERNAME:$GITHUB_TOKEN@github.com" >>  ~/.git-credentials
          cd ./charts/common
          make version
          make tag
          make release
          make github
          make updatebot/push-version
        env:
          GITHUB_USERNAME: ${{ secrets.BOT_GITHUB_USERNAME }}
          GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
