name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the default branch
  push:
    branches: [ master, dev-elias-3898-gh-actions ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  pre-commit:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: Alfresco/alfresco-build-tools/.github/actions/setup-helm-docs@v1.3.0
      - uses: Alfresco/alfresco-build-tools/.github/actions/setup-kubepug@master
      - uses: Alfresco/alfresco-build-tools/.github/actions/setup-checkov@master
      - uses: pre-commit/action@v2.0.3
