name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  CHART_DIR: "charts/common"

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: Alfresco/alfresco-build-tools/.github/actions/setup-helm-docs@v1.22.0
      - uses: Alfresco/alfresco-build-tools/.github/actions/setup-kubepug@v1.22.0
      - uses: bridgecrewio/checkov-action@v12.1839.0
        with:
          framework: kubernetes
      - uses: Alfresco/alfresco-build-tools/.github/actions/pre-commit@v1.22.0

  build:
    runs-on: ubuntu-latest
    needs: pre-commit
    steps:
      - uses: actions/checkout@v3

      - name: Build
        uses: Alfresco/alfresco-build-tools/.github/actions/helm-build-chart@v1.22.0
        with:
          chart-dir: ${{ env.CHART_DIR }}

      - name: Setup Helm test plugin
        run: helm plugin install https://github.com/quintush/helm-unittest

      - name: Test
        run: helm unittest $CHART_DIR --helm3

  parse-next-release:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    needs: build
    outputs:
      next-release: ${{ steps.parse-next-release.outputs.next-release }}
    steps:
      - uses: actions/checkout@v3
      - name: Parse next release
        id: parse-next-release
        uses: Alfresco/alfresco-build-tools/.github/actions/helm-parse-next-release@v1.22.0
        with:
          chart-dir: ${{ env.CHART_DIR }}

  publish:
    if: github.event_name == 'push'
    uses: Alfresco/alfresco-build-tools/.github/workflows/helm-publish-new-package-version.yml@v1.20.3
    needs: parse-next-release
    with:
      next-version: ${{ needs.parse-next-release.outputs.next-release }}
      chart-dir: charts/common
      helm-charts-repo: Activiti/activiti-cloud-helm-charts
      helm-charts-repo-branch: gh-pages
    secrets: inherit

  propagate:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: publish
    env:
      VERSION: ${{ needs.publish.outputs.version }}
      DEVELOPMENT_BRANCH: ${{ github.ref_name }}
    steps:
      - uses: actions/checkout@v3
      - uses: Alfresco/alfresco-build-tools/.github/actions/setup-helm-docs@v1.22.0
      - uses: Alfresco/alfresco-build-tools/.github/actions/jx-updatebot-pr@v1.22.0
        env:
          GH_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
        with:
          version: ${{ env.VERSION }}
          auto-merge: 'true'
          labels: ${{ env.DEVELOPMENT_BRANCH }}
          git-username: ${{ secrets.BOT_GITHUB_USERNAME }}
          git-token: ${{ secrets.BOT_GITHUB_TOKEN }}
          git-author-name: ${{ secrets.BOT_GITHUB_USERNAME }}

  notify:
    runs-on: ubuntu-latest
    needs: propagate
    if: always() && failure() && github.event_name == 'push'
    steps:
      - name: Slack Notification
        uses: Alfresco/alfresco-build-tools/.github/actions/send-slack-notification@v1.22.0
        with:
          channel-id: 'eng-hxp-studio-activiti-gh-notifs'
          token: ${{ secrets.SLACK_NOTIFICATION_BOT_TOKEN }}
